// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/orderpb/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_orderpb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_orderpb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_orderpb_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type FindOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOrderByIDRequest) Reset() {
	*x = FindOrderByIDRequest{}
	mi := &file_proto_orderpb_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderByIDRequest) ProtoMessage() {}

func (x *FindOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*FindOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{3}
}

func (x *FindOrderByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOrderByIDResponse) Reset() {
	*x = FindOrderByIDResponse{}
	mi := &file_proto_orderpb_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderByIDResponse) ProtoMessage() {}

func (x *FindOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*FindOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{4}
}

func (x *FindOrderByIDResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type FindAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrdersRequest) Reset() {
	*x = FindAllOrdersRequest{}
	mi := &file_proto_orderpb_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrdersRequest) ProtoMessage() {}

func (x *FindAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{5}
}

type FindAllOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrdersResponse) Reset() {
	*x = FindAllOrdersResponse{}
	mi := &file_proto_orderpb_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrdersResponse) ProtoMessage() {}

func (x *FindAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*FindAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PatchOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchOrderRequest) Reset() {
	*x = PatchOrderRequest{}
	mi := &file_proto_orderpb_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOrderRequest) ProtoMessage() {}

func (x *PatchOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOrderRequest.ProtoReflect.Descriptor instead.
func (*PatchOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{7}
}

func (x *PatchOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchOrderRequest) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PatchOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchOrderResponse) Reset() {
	*x = PatchOrderResponse{}
	mi := &file_proto_orderpb_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOrderResponse) ProtoMessage() {}

func (x *PatchOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOrderResponse.ProtoReflect.Descriptor instead.
func (*PatchOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{8}
}

func (x *PatchOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_proto_orderpb_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_proto_orderpb_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderpb_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderpb_order_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_orderpb_order_proto protoreflect.FileDescriptor

const file_proto_orderpb_order_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orderpb/order.proto\x12\x05order\"-\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"*\n" +
	"\x12CreateOrderRequest\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\"9\n" +
	"\x13CreateOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"&\n" +
	"\x14FindOrderByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\";\n" +
	"\x15FindOrderByIDResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"\x16\n" +
	"\x14FindAllOrdersRequest\"=\n" +
	"\x15FindAllOrdersResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\"9\n" +
	"\x11PatchOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"8\n" +
	"\x12PatchOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"$\n" +
	"\x12DeleteOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x13DeleteOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf5\x02\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12J\n" +
	"\rFindOrderByID\x12\x1b.order.FindOrderByIDRequest\x1a\x1c.order.FindOrderByIDResponse\x12J\n" +
	"\rFindAllOrders\x12\x1b.order.FindAllOrdersRequest\x1a\x1c.order.FindAllOrdersResponse\x12A\n" +
	"\n" +
	"PatchOrder\x12\x18.order.PatchOrderRequest\x1a\x19.order.PatchOrderResponse\x12D\n" +
	"\vDeleteOrder\x12\x19.order.DeleteOrderRequest\x1a\x1a.order.DeleteOrderResponseB3Z1Notification_Preferences/proto/orderpbb\x06proto3"

var (
	file_proto_orderpb_order_proto_rawDescOnce sync.Once
	file_proto_orderpb_order_proto_rawDescData []byte
)

func file_proto_orderpb_order_proto_rawDescGZIP() []byte {
	file_proto_orderpb_order_proto_rawDescOnce.Do(func() {
		file_proto_orderpb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderpb_order_proto_rawDesc), len(file_proto_orderpb_order_proto_rawDesc)))
	})
	return file_proto_orderpb_order_proto_rawDescData
}

var file_proto_orderpb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_orderpb_order_proto_goTypes = []any{
	(*Order)(nil),                 // 0: order.Order
	(*CreateOrderRequest)(nil),    // 1: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),   // 2: order.CreateOrderResponse
	(*FindOrderByIDRequest)(nil),  // 3: order.FindOrderByIDRequest
	(*FindOrderByIDResponse)(nil), // 4: order.FindOrderByIDResponse
	(*FindAllOrdersRequest)(nil),  // 5: order.FindAllOrdersRequest
	(*FindAllOrdersResponse)(nil), // 6: order.FindAllOrdersResponse
	(*PatchOrderRequest)(nil),     // 7: order.PatchOrderRequest
	(*PatchOrderResponse)(nil),    // 8: order.PatchOrderResponse
	(*DeleteOrderRequest)(nil),    // 9: order.DeleteOrderRequest
	(*DeleteOrderResponse)(nil),   // 10: order.DeleteOrderResponse
}
var file_proto_orderpb_order_proto_depIdxs = []int32{
	0,  // 0: order.CreateOrderResponse.order:type_name -> order.Order
	0,  // 1: order.FindOrderByIDResponse.order:type_name -> order.Order
	0,  // 2: order.FindAllOrdersResponse.orders:type_name -> order.Order
	0,  // 3: order.PatchOrderResponse.order:type_name -> order.Order
	1,  // 4: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	3,  // 5: order.OrderService.FindOrderByID:input_type -> order.FindOrderByIDRequest
	5,  // 6: order.OrderService.FindAllOrders:input_type -> order.FindAllOrdersRequest
	7,  // 7: order.OrderService.PatchOrder:input_type -> order.PatchOrderRequest
	9,  // 8: order.OrderService.DeleteOrder:input_type -> order.DeleteOrderRequest
	2,  // 9: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	4,  // 10: order.OrderService.FindOrderByID:output_type -> order.FindOrderByIDResponse
	6,  // 11: order.OrderService.FindAllOrders:output_type -> order.FindAllOrdersResponse
	8,  // 12: order.OrderService.PatchOrder:output_type -> order.PatchOrderResponse
	10, // 13: order.OrderService.DeleteOrder:output_type -> order.DeleteOrderResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_orderpb_order_proto_init() }
func file_proto_orderpb_order_proto_init() {
	if File_proto_orderpb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderpb_order_proto_rawDesc), len(file_proto_orderpb_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderpb_order_proto_goTypes,
		DependencyIndexes: file_proto_orderpb_order_proto_depIdxs,
		MessageInfos:      file_proto_orderpb_order_proto_msgTypes,
	}.Build()
	File_proto_orderpb_order_proto = out.File
	file_proto_orderpb_order_proto_goTypes = nil
	file_proto_orderpb_order_proto_depIdxs = nil
}
